// Generated by gencpp from file pg70/Move.msg
// DO NOT EDIT!


#ifndef PG70_MESSAGE_MOVE_H
#define PG70_MESSAGE_MOVE_H

#include <ros/service_traits.h>


#include <pg70/MoveRequest.h>
#include <pg70/MoveResponse.h>


namespace pg70
{

struct Move
{

typedef MoveRequest Request;
typedef MoveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Move
} // namespace pg70


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pg70::Move > {
  static const char* value()
  {
    return "6e8de7de8f3900ccfb2f0286718a113d";
  }

  static const char* value(const ::pg70::Move&) { return value(); }
};

template<>
struct DataType< ::pg70::Move > {
  static const char* value()
  {
    return "pg70/Move";
  }

  static const char* value(const ::pg70::Move&) { return value(); }
};


// service_traits::MD5Sum< ::pg70::MoveRequest> should match 
// service_traits::MD5Sum< ::pg70::Move > 
template<>
struct MD5Sum< ::pg70::MoveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pg70::Move >::value();
  }
  static const char* value(const ::pg70::MoveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pg70::MoveRequest> should match 
// service_traits::DataType< ::pg70::Move > 
template<>
struct DataType< ::pg70::MoveRequest>
{
  static const char* value()
  {
    return DataType< ::pg70::Move >::value();
  }
  static const char* value(const ::pg70::MoveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pg70::MoveResponse> should match 
// service_traits::MD5Sum< ::pg70::Move > 
template<>
struct MD5Sum< ::pg70::MoveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pg70::Move >::value();
  }
  static const char* value(const ::pg70::MoveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pg70::MoveResponse> should match 
// service_traits::DataType< ::pg70::Move > 
template<>
struct DataType< ::pg70::MoveResponse>
{
  static const char* value()
  {
    return DataType< ::pg70::Move >::value();
  }
  static const char* value(const ::pg70::MoveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PG70_MESSAGE_MOVE_H
