// Generated by gencpp from file pg70/Open.msg
// DO NOT EDIT!


#ifndef PG70_MESSAGE_OPEN_H
#define PG70_MESSAGE_OPEN_H

#include <ros/service_traits.h>


#include <pg70/OpenRequest.h>
#include <pg70/OpenResponse.h>


namespace pg70
{

struct Open
{

typedef OpenRequest Request;
typedef OpenResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Open
} // namespace pg70


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pg70::Open > {
  static const char* value()
  {
    return "a528deecbc4be6f38cecca3041d9f6b7";
  }

  static const char* value(const ::pg70::Open&) { return value(); }
};

template<>
struct DataType< ::pg70::Open > {
  static const char* value()
  {
    return "pg70/Open";
  }

  static const char* value(const ::pg70::Open&) { return value(); }
};


// service_traits::MD5Sum< ::pg70::OpenRequest> should match 
// service_traits::MD5Sum< ::pg70::Open > 
template<>
struct MD5Sum< ::pg70::OpenRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pg70::Open >::value();
  }
  static const char* value(const ::pg70::OpenRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pg70::OpenRequest> should match 
// service_traits::DataType< ::pg70::Open > 
template<>
struct DataType< ::pg70::OpenRequest>
{
  static const char* value()
  {
    return DataType< ::pg70::Open >::value();
  }
  static const char* value(const ::pg70::OpenRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pg70::OpenResponse> should match 
// service_traits::MD5Sum< ::pg70::Open > 
template<>
struct MD5Sum< ::pg70::OpenResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pg70::Open >::value();
  }
  static const char* value(const ::pg70::OpenResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pg70::OpenResponse> should match 
// service_traits::DataType< ::pg70::Open > 
template<>
struct DataType< ::pg70::OpenResponse>
{
  static const char* value()
  {
    return DataType< ::pg70::Open >::value();
  }
  static const char* value(const ::pg70::OpenResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PG70_MESSAGE_OPEN_H
