// Generated by gencpp from file pg70/OpenRequest.msg
// DO NOT EDIT!


#ifndef PG70_MESSAGE_OPENREQUEST_H
#define PG70_MESSAGE_OPENREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pg70
{
template <class ContainerAllocator>
struct OpenRequest_
{
  typedef OpenRequest_<ContainerAllocator> Type;

  OpenRequest_()
    : power(0.0)  {
    }
  OpenRequest_(const ContainerAllocator& _alloc)
    : power(0.0)  {
  (void)_alloc;
    }



   typedef float _power_type;
  _power_type power;





  typedef boost::shared_ptr< ::pg70::OpenRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pg70::OpenRequest_<ContainerAllocator> const> ConstPtr;

}; // struct OpenRequest_

typedef ::pg70::OpenRequest_<std::allocator<void> > OpenRequest;

typedef boost::shared_ptr< ::pg70::OpenRequest > OpenRequestPtr;
typedef boost::shared_ptr< ::pg70::OpenRequest const> OpenRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pg70::OpenRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pg70::OpenRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pg70

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pg70::OpenRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pg70::OpenRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pg70::OpenRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pg70::OpenRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pg70::OpenRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pg70::OpenRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pg70::OpenRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b75f3bcdec2dcafb6503e9b6316400b0";
  }

  static const char* value(const ::pg70::OpenRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb75f3bcdec2dcafbULL;
  static const uint64_t static_value2 = 0x6503e9b6316400b0ULL;
};

template<class ContainerAllocator>
struct DataType< ::pg70::OpenRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pg70/OpenRequest";
  }

  static const char* value(const ::pg70::OpenRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pg70::OpenRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
float32 power\n\
";
  }

  static const char* value(const ::pg70::OpenRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pg70::OpenRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.power);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OpenRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pg70::OpenRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pg70::OpenRequest_<ContainerAllocator>& v)
  {
    s << indent << "power: ";
    Printer<float>::stream(s, indent + "  ", v.power);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PG70_MESSAGE_OPENREQUEST_H
