// Generated by gencpp from file pg70/Stop.msg
// DO NOT EDIT!


#ifndef PG70_MESSAGE_STOP_H
#define PG70_MESSAGE_STOP_H

#include <ros/service_traits.h>


#include <pg70/StopRequest.h>
#include <pg70/StopResponse.h>


namespace pg70
{

struct Stop
{

typedef StopRequest Request;
typedef StopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Stop
} // namespace pg70


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pg70::Stop > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::pg70::Stop&) { return value(); }
};

template<>
struct DataType< ::pg70::Stop > {
  static const char* value()
  {
    return "pg70/Stop";
  }

  static const char* value(const ::pg70::Stop&) { return value(); }
};


// service_traits::MD5Sum< ::pg70::StopRequest> should match 
// service_traits::MD5Sum< ::pg70::Stop > 
template<>
struct MD5Sum< ::pg70::StopRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pg70::Stop >::value();
  }
  static const char* value(const ::pg70::StopRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pg70::StopRequest> should match 
// service_traits::DataType< ::pg70::Stop > 
template<>
struct DataType< ::pg70::StopRequest>
{
  static const char* value()
  {
    return DataType< ::pg70::Stop >::value();
  }
  static const char* value(const ::pg70::StopRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pg70::StopResponse> should match 
// service_traits::MD5Sum< ::pg70::Stop > 
template<>
struct MD5Sum< ::pg70::StopResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pg70::Stop >::value();
  }
  static const char* value(const ::pg70::StopResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pg70::StopResponse> should match 
// service_traits::DataType< ::pg70::Stop > 
template<>
struct DataType< ::pg70::StopResponse>
{
  static const char* value()
  {
    return DataType< ::pg70::Stop >::value();
  }
  static const char* value(const ::pg70::StopResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PG70_MESSAGE_STOP_H
