// Generated by gencpp from file pa10controller/clearJointQueueRequest.msg
// DO NOT EDIT!


#ifndef PA10CONTROLLER_MESSAGE_CLEARJOINTQUEUEREQUEST_H
#define PA10CONTROLLER_MESSAGE_CLEARJOINTQUEUEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pa10controller
{
template <class ContainerAllocator>
struct clearJointQueueRequest_
{
  typedef clearJointQueueRequest_<ContainerAllocator> Type;

  clearJointQueueRequest_()
    : command(0)  {
    }
  clearJointQueueRequest_(const ContainerAllocator& _alloc)
    : command(0)  {
  (void)_alloc;
    }



   typedef int8_t _command_type;
  _command_type command;



  enum {
    CMD_STOP = 1,
    CMD_FORWARD = 2,
    CMD_REVERSE = 3,
    CMD_GRIP = 4,
    CMD_RELEASE = 5,
  };


  typedef boost::shared_ptr< ::pa10controller::clearJointQueueRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pa10controller::clearJointQueueRequest_<ContainerAllocator> const> ConstPtr;

}; // struct clearJointQueueRequest_

typedef ::pa10controller::clearJointQueueRequest_<std::allocator<void> > clearJointQueueRequest;

typedef boost::shared_ptr< ::pa10controller::clearJointQueueRequest > clearJointQueueRequestPtr;
typedef boost::shared_ptr< ::pa10controller::clearJointQueueRequest const> clearJointQueueRequestConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pa10controller::clearJointQueueRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pa10controller::clearJointQueueRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pa10controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pa10controller::clearJointQueueRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pa10controller::clearJointQueueRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pa10controller::clearJointQueueRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pa10controller::clearJointQueueRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pa10controller::clearJointQueueRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pa10controller::clearJointQueueRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pa10controller::clearJointQueueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3b617c1200bb1268979eb525f44de8b3";
  }

  static const char* value(const ::pa10controller::clearJointQueueRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3b617c1200bb1268ULL;
  static const uint64_t static_value2 = 0x979eb525f44de8b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::pa10controller::clearJointQueueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pa10controller/clearJointQueueRequest";
  }

  static const char* value(const ::pa10controller::clearJointQueueRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pa10controller::clearJointQueueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
int8 CMD_STOP=1\n\
int8 CMD_FORWARD=2\n\
int8 CMD_REVERSE=3\n\
int8 CMD_GRIP=4\n\
int8 CMD_RELEASE=5\n\
\n\
\n\
int8 command\n\
";
  }

  static const char* value(const ::pa10controller::clearJointQueueRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pa10controller::clearJointQueueRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct clearJointQueueRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pa10controller::clearJointQueueRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pa10controller::clearJointQueueRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<int8_t>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PA10CONTROLLER_MESSAGE_CLEARJOINTQUEUEREQUEST_H
