// Generated by gencpp from file pa10controller/clearJointQueue.msg
// DO NOT EDIT!


#ifndef PA10CONTROLLER_MESSAGE_CLEARJOINTQUEUE_H
#define PA10CONTROLLER_MESSAGE_CLEARJOINTQUEUE_H

#include <ros/service_traits.h>


#include <pa10controller/clearJointQueueRequest.h>
#include <pa10controller/clearJointQueueResponse.h>


namespace pa10controller
{

struct clearJointQueue
{

typedef clearJointQueueRequest Request;
typedef clearJointQueueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct clearJointQueue
} // namespace pa10controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pa10controller::clearJointQueue > {
  static const char* value()
  {
    return "c825eadd789321366b3e11633a4f982b";
  }

  static const char* value(const ::pa10controller::clearJointQueue&) { return value(); }
};

template<>
struct DataType< ::pa10controller::clearJointQueue > {
  static const char* value()
  {
    return "pa10controller/clearJointQueue";
  }

  static const char* value(const ::pa10controller::clearJointQueue&) { return value(); }
};


// service_traits::MD5Sum< ::pa10controller::clearJointQueueRequest> should match 
// service_traits::MD5Sum< ::pa10controller::clearJointQueue > 
template<>
struct MD5Sum< ::pa10controller::clearJointQueueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pa10controller::clearJointQueue >::value();
  }
  static const char* value(const ::pa10controller::clearJointQueueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pa10controller::clearJointQueueRequest> should match 
// service_traits::DataType< ::pa10controller::clearJointQueue > 
template<>
struct DataType< ::pa10controller::clearJointQueueRequest>
{
  static const char* value()
  {
    return DataType< ::pa10controller::clearJointQueue >::value();
  }
  static const char* value(const ::pa10controller::clearJointQueueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pa10controller::clearJointQueueResponse> should match 
// service_traits::MD5Sum< ::pa10controller::clearJointQueue > 
template<>
struct MD5Sum< ::pa10controller::clearJointQueueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pa10controller::clearJointQueue >::value();
  }
  static const char* value(const ::pa10controller::clearJointQueueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pa10controller::clearJointQueueResponse> should match 
// service_traits::DataType< ::pa10controller::clearJointQueue > 
template<>
struct DataType< ::pa10controller::clearJointQueueResponse>
{
  static const char* value()
  {
    return DataType< ::pa10controller::clearJointQueue >::value();
  }
  static const char* value(const ::pa10controller::clearJointQueueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PA10CONTROLLER_MESSAGE_CLEARJOINTQUEUE_H
