// Generated by gencpp from file pa10controller/getJointConfigResponse.msg
// DO NOT EDIT!


#ifndef PA10CONTROLLER_MESSAGE_GETJOINTCONFIGRESPONSE_H
#define PA10CONTROLLER_MESSAGE_GETJOINTCONFIGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pa10controller
{
template <class ContainerAllocator>
struct getJointConfigResponse_
{
  typedef getJointConfigResponse_<ContainerAllocator> Type;

  getJointConfigResponse_()
    : positions()
    , commands()  {
      positions.assign(0.0);

      commands.assign(0.0);
  }
  getJointConfigResponse_(const ContainerAllocator& _alloc)
    : positions()
    , commands()  {
  (void)_alloc;
      positions.assign(0.0);

      commands.assign(0.0);
  }



   typedef boost::array<float, 7>  _positions_type;
  _positions_type positions;

   typedef boost::array<float, 7>  _commands_type;
  _commands_type commands;





  typedef boost::shared_ptr< ::pa10controller::getJointConfigResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pa10controller::getJointConfigResponse_<ContainerAllocator> const> ConstPtr;

}; // struct getJointConfigResponse_

typedef ::pa10controller::getJointConfigResponse_<std::allocator<void> > getJointConfigResponse;

typedef boost::shared_ptr< ::pa10controller::getJointConfigResponse > getJointConfigResponsePtr;
typedef boost::shared_ptr< ::pa10controller::getJointConfigResponse const> getJointConfigResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pa10controller::getJointConfigResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pa10controller::getJointConfigResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pa10controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pa10controller::getJointConfigResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pa10controller::getJointConfigResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pa10controller::getJointConfigResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pa10controller::getJointConfigResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pa10controller::getJointConfigResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pa10controller::getJointConfigResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pa10controller::getJointConfigResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b59e38f5296df3482c671e5301fa089";
  }

  static const char* value(const ::pa10controller::getJointConfigResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b59e38f5296df34ULL;
  static const uint64_t static_value2 = 0x82c671e5301fa089ULL;
};

template<class ContainerAllocator>
struct DataType< ::pa10controller::getJointConfigResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pa10controller/getJointConfigResponse";
  }

  static const char* value(const ::pa10controller::getJointConfigResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pa10controller::getJointConfigResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
float32[7] positions\n\
float32[7] commands\n\
";
  }

  static const char* value(const ::pa10controller::getJointConfigResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pa10controller::getJointConfigResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.positions);
      stream.next(m.commands);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct getJointConfigResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pa10controller::getJointConfigResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pa10controller::getJointConfigResponse_<ContainerAllocator>& v)
  {
    s << indent << "positions[]" << std::endl;
    for (size_t i = 0; i < v.positions.size(); ++i)
    {
      s << indent << "  positions[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.positions[i]);
    }
    s << indent << "commands[]" << std::endl;
    for (size_t i = 0; i < v.commands.size(); ++i)
    {
      s << indent << "  commands[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.commands[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PA10CONTROLLER_MESSAGE_GETJOINTCONFIGRESPONSE_H
