// Generated by gencpp from file pa10controller/setJointConfig.msg
// DO NOT EDIT!


#ifndef PA10CONTROLLER_MESSAGE_SETJOINTCONFIG_H
#define PA10CONTROLLER_MESSAGE_SETJOINTCONFIG_H

#include <ros/service_traits.h>


#include <pa10controller/setJointConfigRequest.h>
#include <pa10controller/setJointConfigResponse.h>


namespace pa10controller
{

struct setJointConfig
{

typedef setJointConfigRequest Request;
typedef setJointConfigResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct setJointConfig
} // namespace pa10controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pa10controller::setJointConfig > {
  static const char* value()
  {
    return "46282454b294ac7d0c48434b1d003f7a";
  }

  static const char* value(const ::pa10controller::setJointConfig&) { return value(); }
};

template<>
struct DataType< ::pa10controller::setJointConfig > {
  static const char* value()
  {
    return "pa10controller/setJointConfig";
  }

  static const char* value(const ::pa10controller::setJointConfig&) { return value(); }
};


// service_traits::MD5Sum< ::pa10controller::setJointConfigRequest> should match 
// service_traits::MD5Sum< ::pa10controller::setJointConfig > 
template<>
struct MD5Sum< ::pa10controller::setJointConfigRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pa10controller::setJointConfig >::value();
  }
  static const char* value(const ::pa10controller::setJointConfigRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pa10controller::setJointConfigRequest> should match 
// service_traits::DataType< ::pa10controller::setJointConfig > 
template<>
struct DataType< ::pa10controller::setJointConfigRequest>
{
  static const char* value()
  {
    return DataType< ::pa10controller::setJointConfig >::value();
  }
  static const char* value(const ::pa10controller::setJointConfigRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pa10controller::setJointConfigResponse> should match 
// service_traits::MD5Sum< ::pa10controller::setJointConfig > 
template<>
struct MD5Sum< ::pa10controller::setJointConfigResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pa10controller::setJointConfig >::value();
  }
  static const char* value(const ::pa10controller::setJointConfigResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pa10controller::setJointConfigResponse> should match 
// service_traits::DataType< ::pa10controller::setJointConfig > 
template<>
struct DataType< ::pa10controller::setJointConfigResponse>
{
  static const char* value()
  {
    return DataType< ::pa10controller::setJointConfig >::value();
  }
  static const char* value(const ::pa10controller::setJointConfigResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PA10CONTROLLER_MESSAGE_SETJOINTCONFIG_H
