// Generated by gencpp from file pa10controller/startQueue.msg
// DO NOT EDIT!


#ifndef PA10CONTROLLER_MESSAGE_STARTQUEUE_H
#define PA10CONTROLLER_MESSAGE_STARTQUEUE_H

#include <ros/service_traits.h>


#include <pa10controller/startQueueRequest.h>
#include <pa10controller/startQueueResponse.h>


namespace pa10controller
{

struct startQueue
{

typedef startQueueRequest Request;
typedef startQueueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct startQueue
} // namespace pa10controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pa10controller::startQueue > {
  static const char* value()
  {
    return "a044a606792641e1aa8c4251ea3f515b";
  }

  static const char* value(const ::pa10controller::startQueue&) { return value(); }
};

template<>
struct DataType< ::pa10controller::startQueue > {
  static const char* value()
  {
    return "pa10controller/startQueue";
  }

  static const char* value(const ::pa10controller::startQueue&) { return value(); }
};


// service_traits::MD5Sum< ::pa10controller::startQueueRequest> should match 
// service_traits::MD5Sum< ::pa10controller::startQueue > 
template<>
struct MD5Sum< ::pa10controller::startQueueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pa10controller::startQueue >::value();
  }
  static const char* value(const ::pa10controller::startQueueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pa10controller::startQueueRequest> should match 
// service_traits::DataType< ::pa10controller::startQueue > 
template<>
struct DataType< ::pa10controller::startQueueRequest>
{
  static const char* value()
  {
    return DataType< ::pa10controller::startQueue >::value();
  }
  static const char* value(const ::pa10controller::startQueueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pa10controller::startQueueResponse> should match 
// service_traits::MD5Sum< ::pa10controller::startQueue > 
template<>
struct MD5Sum< ::pa10controller::startQueueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pa10controller::startQueue >::value();
  }
  static const char* value(const ::pa10controller::startQueueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pa10controller::startQueueResponse> should match 
// service_traits::DataType< ::pa10controller::startQueue > 
template<>
struct DataType< ::pa10controller::startQueueResponse>
{
  static const char* value()
  {
    return DataType< ::pa10controller::startQueue >::value();
  }
  static const char* value(const ::pa10controller::startQueueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PA10CONTROLLER_MESSAGE_STARTQUEUE_H
