// Generated by gencpp from file pa10controller/startPA10.msg
// DO NOT EDIT!


#ifndef PA10CONTROLLER_MESSAGE_STARTPA10_H
#define PA10CONTROLLER_MESSAGE_STARTPA10_H

#include <ros/service_traits.h>


#include <pa10controller/startPA10Request.h>
#include <pa10controller/startPA10Response.h>


namespace pa10controller
{

struct startPA10
{

typedef startPA10Request Request;
typedef startPA10Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct startPA10
} // namespace pa10controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pa10controller::startPA10 > {
  static const char* value()
  {
    return "9d8061d2347621a6ed88451e28811cc7";
  }

  static const char* value(const ::pa10controller::startPA10&) { return value(); }
};

template<>
struct DataType< ::pa10controller::startPA10 > {
  static const char* value()
  {
    return "pa10controller/startPA10";
  }

  static const char* value(const ::pa10controller::startPA10&) { return value(); }
};


// service_traits::MD5Sum< ::pa10controller::startPA10Request> should match 
// service_traits::MD5Sum< ::pa10controller::startPA10 > 
template<>
struct MD5Sum< ::pa10controller::startPA10Request>
{
  static const char* value()
  {
    return MD5Sum< ::pa10controller::startPA10 >::value();
  }
  static const char* value(const ::pa10controller::startPA10Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::pa10controller::startPA10Request> should match 
// service_traits::DataType< ::pa10controller::startPA10 > 
template<>
struct DataType< ::pa10controller::startPA10Request>
{
  static const char* value()
  {
    return DataType< ::pa10controller::startPA10 >::value();
  }
  static const char* value(const ::pa10controller::startPA10Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pa10controller::startPA10Response> should match 
// service_traits::MD5Sum< ::pa10controller::startPA10 > 
template<>
struct MD5Sum< ::pa10controller::startPA10Response>
{
  static const char* value()
  {
    return MD5Sum< ::pa10controller::startPA10 >::value();
  }
  static const char* value(const ::pa10controller::startPA10Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::pa10controller::startPA10Response> should match 
// service_traits::DataType< ::pa10controller::startPA10 > 
template<>
struct DataType< ::pa10controller::startPA10Response>
{
  static const char* value()
  {
    return DataType< ::pa10controller::startPA10 >::value();
  }
  static const char* value(const ::pa10controller::startPA10Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PA10CONTROLLER_MESSAGE_STARTPA10_H
