// Generated by gencpp from file pa10controller/startQueueRequest.msg
// DO NOT EDIT!


#ifndef PA10CONTROLLER_MESSAGE_STARTQUEUEREQUEST_H
#define PA10CONTROLLER_MESSAGE_STARTQUEUEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pa10controller
{
template <class ContainerAllocator>
struct startQueueRequest_
{
  typedef startQueueRequest_<ContainerAllocator> Type;

  startQueueRequest_()
    : command(false)  {
    }
  startQueueRequest_(const ContainerAllocator& _alloc)
    : command(false)  {
  (void)_alloc;
    }



   typedef uint8_t _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::pa10controller::startQueueRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pa10controller::startQueueRequest_<ContainerAllocator> const> ConstPtr;

}; // struct startQueueRequest_

typedef ::pa10controller::startQueueRequest_<std::allocator<void> > startQueueRequest;

typedef boost::shared_ptr< ::pa10controller::startQueueRequest > startQueueRequestPtr;
typedef boost::shared_ptr< ::pa10controller::startQueueRequest const> startQueueRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pa10controller::startQueueRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pa10controller::startQueueRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pa10controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pa10controller::startQueueRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pa10controller::startQueueRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pa10controller::startQueueRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pa10controller::startQueueRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pa10controller::startQueueRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pa10controller::startQueueRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pa10controller::startQueueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "01134d7a2df15c0112a6a1d7df9d666d";
  }

  static const char* value(const ::pa10controller::startQueueRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x01134d7a2df15c01ULL;
  static const uint64_t static_value2 = 0x12a6a1d7df9d666dULL;
};

template<class ContainerAllocator>
struct DataType< ::pa10controller::startQueueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pa10controller/startQueueRequest";
  }

  static const char* value(const ::pa10controller::startQueueRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pa10controller::startQueueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
\n\
bool command\n\
";
  }

  static const char* value(const ::pa10controller::startQueueRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pa10controller::startQueueRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct startQueueRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pa10controller::startQueueRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pa10controller::startQueueRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PA10CONTROLLER_MESSAGE_STARTQUEUEREQUEST_H
