// Generated by gencpp from file pa10controller/startPA10Request.msg
// DO NOT EDIT!


#ifndef PA10CONTROLLER_MESSAGE_STARTPA10REQUEST_H
#define PA10CONTROLLER_MESSAGE_STARTPA10REQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pa10controller
{
template <class ContainerAllocator>
struct startPA10Request_
{
  typedef startPA10Request_<ContainerAllocator> Type;

  startPA10Request_()
    {
    }
  startPA10Request_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::pa10controller::startPA10Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pa10controller::startPA10Request_<ContainerAllocator> const> ConstPtr;

}; // struct startPA10Request_

typedef ::pa10controller::startPA10Request_<std::allocator<void> > startPA10Request;

typedef boost::shared_ptr< ::pa10controller::startPA10Request > startPA10RequestPtr;
typedef boost::shared_ptr< ::pa10controller::startPA10Request const> startPA10RequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pa10controller::startPA10Request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pa10controller::startPA10Request_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pa10controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pa10controller::startPA10Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pa10controller::startPA10Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pa10controller::startPA10Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pa10controller::startPA10Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pa10controller::startPA10Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pa10controller::startPA10Request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pa10controller::startPA10Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::pa10controller::startPA10Request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::pa10controller::startPA10Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pa10controller/startPA10Request";
  }

  static const char* value(const ::pa10controller::startPA10Request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pa10controller::startPA10Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::pa10controller::startPA10Request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pa10controller::startPA10Request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct startPA10Request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pa10controller::startPA10Request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::pa10controller::startPA10Request_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // PA10CONTROLLER_MESSAGE_STARTPA10REQUEST_H
