# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from pa10controller/addToQueueRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class addToQueueRequest(genpy.Message):
  _md5sum = "cb607eed6d73397ca138f7e25e56c188"
  _type = "pa10controller/addToQueueRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """

bool gripper
bool endOfQueue
float32[7] positions
float32[7] commands
"""
  __slots__ = ['gripper','endOfQueue','positions','commands']
  _slot_types = ['bool','bool','float32[7]','float32[7]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       gripper,endOfQueue,positions,commands

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(addToQueueRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.gripper is None:
        self.gripper = False
      if self.endOfQueue is None:
        self.endOfQueue = False
      if self.positions is None:
        self.positions = [0.] * 7
      if self.commands is None:
        self.commands = [0.] * 7
    else:
      self.gripper = False
      self.endOfQueue = False
      self.positions = [0.] * 7
      self.commands = [0.] * 7

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2B().pack(_x.gripper, _x.endOfQueue))
      buff.write(_get_struct_7f().pack(*self.positions))
      buff.write(_get_struct_7f().pack(*self.commands))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.gripper, _x.endOfQueue,) = _get_struct_2B().unpack(str[start:end])
      self.gripper = bool(self.gripper)
      self.endOfQueue = bool(self.endOfQueue)
      start = end
      end += 28
      self.positions = _get_struct_7f().unpack(str[start:end])
      start = end
      end += 28
      self.commands = _get_struct_7f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2B().pack(_x.gripper, _x.endOfQueue))
      buff.write(self.positions.tostring())
      buff.write(self.commands.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.gripper, _x.endOfQueue,) = _get_struct_2B().unpack(str[start:end])
      self.gripper = bool(self.gripper)
      self.endOfQueue = bool(self.endOfQueue)
      start = end
      end += 28
      self.positions = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=7)
      start = end
      end += 28
      self.commands = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=7)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7f = None
def _get_struct_7f():
    global _struct_7f
    if _struct_7f is None:
        _struct_7f = struct.Struct("<7f")
    return _struct_7f
_struct_2B = None
def _get_struct_2B():
    global _struct_2B
    if _struct_2B is None:
        _struct_2B = struct.Struct("<2B")
    return _struct_2B
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from pa10controller/addToQueueResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class addToQueueResponse(genpy.Message):
  _md5sum = "3e8ad2f62d0edf01ac96b1e92459b490"
  _type = "pa10controller/addToQueueResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """

bool sucess
"""
  __slots__ = ['sucess']
  _slot_types = ['bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       sucess

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(addToQueueResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.sucess is None:
        self.sucess = False
    else:
      self.sucess = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_B().pack(self.sucess))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 1
      (self.sucess,) = _get_struct_B().unpack(str[start:end])
      self.sucess = bool(self.sucess)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_get_struct_B().pack(self.sucess))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 1
      (self.sucess,) = _get_struct_B().unpack(str[start:end])
      self.sucess = bool(self.sucess)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
class addToQueue(object):
  _type          = 'pa10controller/addToQueue'
  _md5sum = '3c31d885a63f71726d73c88c92dde354'
  _request_class  = addToQueueRequest
  _response_class = addToQueueResponse
